spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/fichepolice
    username: postgres
    password: passer
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC

app:
  base-url: "http://localhost:8080"